### ISSUE TITLE
Custom actions don't work

### ISSUE THREAD

**Issue by adrianofoschi** [tibirna/qgit#12]
Hello, I started QGit from terminal and I setted a simple "my custom action" as follow:

`git pull`

But on custom action click I receive this error in console:

`ASSERT in customAction_activated, action &my custom action not found`

It happens with every action.
I'm using official x86_64 package on archlinux.

https://www.archlinux.org/packages/community/x86_64/qgit/

**Comment by tibirna** [comment]
Thanks for this.

I can reproduce it. The cause is that something changes the name of the action from what you give to something containing the accelerator mark (in your case from 'git pull' to '&git pull').

I recall that KDE had a Qt plugin that did just that. So this might cause your issue if you are running KDE or some application that drags in that plugin.

An immediate workaround for you is to manually specify the accelerator mark when you define your command. In the above case, give explicitly '&git pull' as action name.

I will look for a reliable fix and put it in the next release.

Thanks

**Comment by adrianofoschi** [comment]
I see that you've just fix it :)
I created a -git version of package in Archlinux AUR repository and it works perfectly.

https://aur.archlinux.org/packages/qgit-git

Thanks you
