### ISSUE TITLE
QGit release 2.10? — Please please :)

### ISSUE THREAD

**Issue by hartwork** [tibirna/qgit#121]
Hi @tibirna, happy new year!

There are [60+ unreleased commits on `master`](https://github.com/tibirna/qgit/compare/qgit-2.9...master) since latest release QGit 2.9. Especially with non-rolling distributions of Linux in mind that have stabilization cycles and will not apply anything but security fixes, it would be awesome to have a new release QGit 2.10 so that the changes of last year reach the larger use base. Any chance?

Thanks and best, Sebastian

**Comment by tibirna** [comment]
Happy New Year to you too, Sebastian!

I agree, a new tagging is needed for quite some time, already. I procrastinated on this because I wanted to get a bit more testing done on the multiple changes added.

I will do some testing over the week-end and I will tag the next release immediately afterwards.

Thanks for the gentle prodding :-)
Cristian

**Comment by hartwork** [comment]
@tibirna that sounds great, thank you! :pray:

**Comment by tibirna** [comment]
https://github.com/tibirna/qgit/releases/tag/qgit-2.10

**Comment by hartwork** [comment]
@tibirna thank you! :pray:

**Comment by hartwork** [comment]
@tibirna FYI 2.10 [just hit Gentoo](https://github.com/gentoo/gentoo/commit/9420d8550979bfaea8060c085a2e031414258369). Btw this page is a nice place to see where distros are with updating QGit: https://repology.org/project/qgit/versions . Ignore me if you know repology.org already :smile:

**Comment by tibirna** [comment]
Thank you very much. I think I knew about repology but I tend to forget, so thanks a lot for the reminder.
