### ISSUE TITLE
Salvaged from old home: typing 'G' repeatedly crashes QGit compiled with Qt5

### ISSUE THREAD

**Issue by tibirna** [tibirna/qgit#21]
How to reproduce:
* have QGit compiled (with Qt5) from the "compile_with_Qt5"
* open the qgit git repo
* click on a revision
* type 'G' a few times => the treeview seems to change focus as if this triggered a search
* after a few times typing 'G', *QGit crashes*.

**Comment by filiperinaldi** [comment]
I tried it on both MacOS (QT 5.10.1) and Linux (QT 5.9.1) and it does not crash. As you mentioned, it changes focus (as it keeps going on searching for 'g') but that is it, no crashes for me. Was it perhaps a broken version of QT since this is a built-in search support (QAbstractItemView::keyboardSearch())?

**Comment by tibirna** [comment]
Can't reproduce. It _might_ be something particular to original reporter's exact git repo the issue was experienced on. No way to know now. There were multiple changes in the code since 2018 too.
