### ISSUE TITLE
No way to view patches in the per file history

### ISSUE THREAD

**Issue by ffesti** [tibirna/qgit#58]
When viewing the patches for a given file (after double clicking on the file in the "Git tree") one would expect that double clicking on a commit would show the commit/patch. Instead it brings up the full list of commits. This may have been useful at some point - and may still be - if the commit was selected there. Unfortunately it is not but the list is on whatever was selected previously.

I suggest to not go to the full list at all but just open the commit directly in the "Patch" tab - the same way as when double clicking on the full commit list. The patch could also be selected in the full commit list to be able to access the surrounding patches (assuming the patch is visible in there and not filtered out)

**Comment by tibirna** [comment]
I can't reproduce this. The full history of commits is indeed brought up, but with the double clicked commit from the file's commit list selected. Of course, this also shows the patch of the commit in the bottom half if not configured otherwise (i.e. if split view is on).

Also, you can see directly the patch by using the context menu (right click) or the Ctrl+P keyboard shortcut.
