### ISSUE TITLE
Recover gracefully from corrupted cache situations

### ISSUE THREAD

**Issue by tibirna** [tibirna/qgit#71]
If the cache file (`.git/qgit_cache.dat`) gets corrupted in some way (e.g. file truncated or crash in the middle of saving it), qgit can't be started anymore on the affected repository, crashing in the cache reading process.

TODO: wrap all cache process in a `try...catch...` and simply reconstruct cache on any error. If recovery process fails, forego use of cache and inform user for further investigation.

Related issue: #69

**Comment by yuyichao** [comment]
A related issue and the root cause of the crash is that the cache loading process corrupts the memory when invalid cache is encountered and it may not be good enough to simply retry.

This happens because [`Cache::load`](https://github.com/tibirna/qgit/blob/8b3b8225d1400a06a3df3cd4655dcf4e208a3218/src/cache.cpp#L154-L155) stored a raw pointer from the sha buffer into the global cache (i.e. `revsFiles`). However, if the reads errors, [the caller (`Git::loadFileCache`)](https://github.com/tibirna/qgit/blob/8b3b8225d1400a06a3df3cd4655dcf4e208a3218/src/git.cpp#L2528-L2532) does not keep this buffer alive so as soon as `loadFileCache` returns the cache is already corrupted and must not be looked at again (every keys in the hash table becomes invalid AFAICT). The solution to this problem would be to unconditionally preserve the `shaBuf` or revert all changes to the cache immediately.

It also seems that the reader of the shas does not care check bound and [simply forward the pointer by 41 bytes every cycle](https://github.com/tibirna/qgit/blob/8b3b8225d1400a06a3df3cd4655dcf4e208a3218/src/cache.cpp#L157). A bounds check should probably be added...

**Comment by yuyichao** [comment]
And just for the reference, the cause for my corrupted cache file may be openning multiple qgit on the same checkout at the same time, or using complex options to filter the commits (`--not`, `--branches`, `--remotes=*`, etc) or a combination of both. Clearing the cache (or let `qgit` do it automatically with #103) fixes the problem and trying the command line options I've used before did not reproduce it.

In this case, the fresh cache file is 4.1kB whereas the old one was 1.8MB so the currupted one is clearly not just truncated.
